#FROM hfs-dtr-dev.ntrs.com/hfs/nodebuildimage:v1 as builder
FROM ubuntu:20.04

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

RUN apt-get update -y && \
    apt-get install -y python3-pip &&\
    apt-get install -y python3

COPY ./requirements.txt .

RUN pip3 install -r requirements.txt

EXPOSE 8080
